from pykomfovent import KomfoventState


def test_state_is_on_true() -> None:
    state = KomfoventState(
        mode="NORMALNY",
        supply_temp=None,
        extract_temp=None,
        outdoor_temp=None,
        supply_temp_setpoint=None,
        extract_temp_setpoint=None,
        supply_fan_percent=None,
        extract_fan_percent=None,
        supply_fan_intensity=None,
        extract_fan_intensity=None,
        heat_exchanger_percent=None,
        electric_heater_percent=None,
        filter_contamination=None,
        heat_exchanger_efficiency=None,
        heat_recovery_power=None,
        power_consumption=None,
        heating_power=None,
        spi_actual=None,
        spi_daily=None,
        energy_consumed_daily=None,
        energy_consumed_monthly=None,
        energy_consumed_total=None,
        energy_heating_daily=None,
        energy_heating_monthly=None,
        energy_heating_total=None,
        energy_recovered_daily=None,
        energy_recovered_monthly=None,
        energy_recovered_total=None,
        air_quality=None,
        humidity=None,
        flags=0,
    )
    assert state.is_on is True


def test_state_is_on_false_off() -> None:
    state = KomfoventState(
        mode="OFF",
        supply_temp=None,
        extract_temp=None,
        outdoor_temp=None,
        supply_temp_setpoint=None,
        extract_temp_setpoint=None,
        supply_fan_percent=None,
        extract_fan_percent=None,
        supply_fan_intensity=None,
        extract_fan_intensity=None,
        heat_exchanger_percent=None,
        electric_heater_percent=None,
        filter_contamination=None,
        heat_exchanger_efficiency=None,
        heat_recovery_power=None,
        power_consumption=None,
        heating_power=None,
        spi_actual=None,
        spi_daily=None,
        energy_consumed_daily=None,
        energy_consumed_monthly=None,
        energy_consumed_total=None,
        energy_heating_daily=None,
        energy_heating_monthly=None,
        energy_heating_total=None,
        energy_recovered_daily=None,
        energy_recovered_monthly=None,
        energy_recovered_total=None,
        air_quality=None,
        humidity=None,
        flags=0,
    )
    assert state.is_on is False


def test_state_is_on_false_empty() -> None:
    state = KomfoventState(
        mode="",
        supply_temp=None,
        extract_temp=None,
        outdoor_temp=None,
        supply_temp_setpoint=None,
        extract_temp_setpoint=None,
        supply_fan_percent=None,
        extract_fan_percent=None,
        supply_fan_intensity=None,
        extract_fan_intensity=None,
        heat_exchanger_percent=None,
        electric_heater_percent=None,
        filter_contamination=None,
        heat_exchanger_efficiency=None,
        heat_recovery_power=None,
        power_consumption=None,
        heating_power=None,
        spi_actual=None,
        spi_daily=None,
        energy_consumed_daily=None,
        energy_consumed_monthly=None,
        energy_consumed_total=None,
        energy_heating_daily=None,
        energy_heating_monthly=None,
        energy_heating_total=None,
        energy_recovered_daily=None,
        energy_recovered_monthly=None,
        energy_recovered_total=None,
        air_quality=None,
        humidity=None,
        flags=0,
    )
    assert state.is_on is False


def test_state_heating_active_true() -> None:
    state = KomfoventState(
        mode="NORMALNY",
        supply_temp=None,
        extract_temp=None,
        outdoor_temp=None,
        supply_temp_setpoint=None,
        extract_temp_setpoint=None,
        supply_fan_percent=None,
        extract_fan_percent=None,
        supply_fan_intensity=None,
        extract_fan_intensity=None,
        heat_exchanger_percent=None,
        electric_heater_percent=50.0,
        filter_contamination=None,
        heat_exchanger_efficiency=None,
        heat_recovery_power=None,
        power_consumption=None,
        heating_power=100.0,
        spi_actual=None,
        spi_daily=None,
        energy_consumed_daily=None,
        energy_consumed_monthly=None,
        energy_consumed_total=None,
        energy_heating_daily=None,
        energy_heating_monthly=None,
        energy_heating_total=None,
        energy_recovered_daily=None,
        energy_recovered_monthly=None,
        energy_recovered_total=None,
        air_quality=None,
        humidity=None,
        flags=0,
    )
    assert state.heating_active is True


def test_state_heating_active_false() -> None:
    state = KomfoventState(
        mode="NORMALNY",
        supply_temp=None,
        extract_temp=None,
        outdoor_temp=None,
        supply_temp_setpoint=None,
        extract_temp_setpoint=None,
        supply_fan_percent=None,
        extract_fan_percent=None,
        supply_fan_intensity=None,
        extract_fan_intensity=None,
        heat_exchanger_percent=None,
        electric_heater_percent=0.0,
        filter_contamination=None,
        heat_exchanger_efficiency=None,
        heat_recovery_power=None,
        power_consumption=None,
        heating_power=0.0,
        spi_actual=None,
        spi_daily=None,
        energy_consumed_daily=None,
        energy_consumed_monthly=None,
        energy_consumed_total=None,
        energy_heating_daily=None,
        energy_heating_monthly=None,
        energy_heating_total=None,
        energy_recovered_daily=None,
        energy_recovered_monthly=None,
        energy_recovered_total=None,
        air_quality=None,
        humidity=None,
        flags=0,
    )
    assert state.heating_active is False


def test_state_eco_mode() -> None:
    state = KomfoventState(
        mode="NORMALNY",
        supply_temp=None,
        extract_temp=None,
        outdoor_temp=None,
        supply_temp_setpoint=None,
        extract_temp_setpoint=None,
        supply_fan_percent=None,
        extract_fan_percent=None,
        supply_fan_intensity=None,
        extract_fan_intensity=None,
        heat_exchanger_percent=None,
        electric_heater_percent=None,
        filter_contamination=None,
        heat_exchanger_efficiency=None,
        heat_recovery_power=None,
        power_consumption=None,
        heating_power=None,
        spi_actual=None,
        spi_daily=None,
        energy_consumed_daily=None,
        energy_consumed_monthly=None,
        energy_consumed_total=None,
        energy_heating_daily=None,
        energy_heating_monthly=None,
        energy_heating_total=None,
        energy_recovered_daily=None,
        energy_recovered_monthly=None,
        energy_recovered_total=None,
        air_quality=None,
        humidity=None,
        flags=4,  # bit 2 set
    )
    assert state.eco_mode is True
